---
- name: Creer le fichier de configuration Galera
  template:
    src: 60-galera.cnf
    dest: /etc/mysql/mariadb.conf.d/60-galera.cnf
    owner: root
    group: root
    mode: '0644'

- name: Arreter MariaDB si galeranode1
  service:
    name: mariadb
    state: stopped

- name: Demarrer le cluster si galeranode1
  shell: |
    sudo galera_new_cluster

