---
- name: Lancer la VM avec Vagrant
  hosts: localhost
  become: false
  tasks:
    - name: Lancer la machine Vagrant
      command: vagrant up
      args:
        chdir: /home/etudis/Bureau/PHPmyadmin/phpmyadmin/

- name: Attente des machines distantes
  hosts: phpmyadmin
  gather_facts: false
  tasks:
    - name: Attendre que la machine soit accessible en SSH
      wait_for_connection:
        timeout: 5
      register: ssh_check
      until: ssh_check is succeeded
      retries: 30
      delay: 5


- import_playbook: phpmyadmin.yml
- import_playbook: agent_zabbix.yml
