---
- name: Install Apache2 and required modules
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - apache2
    - libapache2-mod-jk

- name: Enable required Apache modules
  command: a2enmod {{ item }}
  with_items:
    - proxy
    - proxy_http
    - proxy_ajp
    - rewrite
    - deflate
    - headers
    - proxy_balancer
    - proxy_connect
    - proxy_html
  notify:
    - restart apache

- name: Configure Apache to work with Tomcat
  template:
    src: apache-tomcat.conf.j2
    dest: /etc/apache2/conf-available/tomcat.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart apache

- name: Enable the Tomcat configuration
  file:
    src: /etc/apache2/conf-available/tomcat.conf
    dest: /etc/apache2/conf-enabled/tomcat.conf
    state: link
  notify:
    - restart apache

- name: Ensure Apache is running and enabled on boot
  service:
    name: apache2
    state: started
    enabled: yes
