---
- name: Lancer la VM avec Vagrant
  hosts: localhost
  become: false
  tasks:
    - name: Lancer la machine Vagrant
      command: vagrant up
      args:
        chdir: /home/etudis/Bureau/vagrant/
      register: vagrant_up
      changed_when: false
      retries: 3
      delay: 10
      until: vagrant_up is succeeded

    - name: Attendre que le port SSH (22) soit disponible sur la VM
      wait_for:
        host: "{{ groups['web'][0] }}"
        port: 22
        state: started
        delay: 10
        timeout: 300
      register: wait_ssh
      retries: 10
      delay: 15
      until: wait_ssh is succeeded

    # Attendre un peu plus pour que le système d'init se charge complètement
    - name: Attendre que la VM soit complètement initialisée
      pause:
        seconds: 5
      when: wait_ssh is succeeded

- name: Configuration du système
  hosts: web
  gather_facts: true
  become: true
  vars:
    max_retries: 10
    retry_delay: 30
    connection_timeout: 300

  # Configuration de la stratégie de reprise
  max_fail_percentage: 0
  force_handlers: true

  pre_tasks:
    - name: Essai de connexion SSH avec réessais
      wait_for_connection:
        delay: 5
        timeout: 30
      register: connection_result
      retries: 5
      delay: 10
      until: connection_result is not failed
      ignore_errors: yes

    - name: Vérifier si la connexion a réussi
      fail:
        msg: |
          Impossible de se connecter à la VM après plusieurs tentatives.
          Vérifiez que :
          - La VM est bien démarrée
          - Le service SSH est actif (systemctl status sshd)
          - Le pare-feu autorise les connexions sur le port 22 (sudo ufw status)
          - L'IP est correcte : {{ inventory_hostname }}
          - Le service réseau est actif (systemctl status systemd-networkd)
      when: connection_result is defined and connection_result is failed

  roles:
    - { role: sys }
    - { role: users }  # Ce rôle inclut déjà le stockage des clés SSH via store_ssh_keys.yml


- import_playbook: system.yml
- import_playbook: apache.yml
- import_playbook: agent_zabbix.yml
