---
- name: Install Tomcat
  apt:
    name: "{{ tomcat_package }}"
    state: present
    update_cache: yes

- name: Ensure Tomcat service is enabled and started
  service:
    name: "{{ tomcat_package }}"
    state: started
    enabled: yes

- name: Configure Tomcat users
  copy:
    dest: /etc/{{ tomcat_package }}/tomcat-users.xml
    content: |
      <?xml version='1.0' encoding='utf-8'?>
      <tomcat-users>
        <role rolename="manager-gui"/>
        <role rolename="admin-gui"/>
        <user username="admin" password="admin" roles="manager-gui,admin-gui"/>
      </tomcat-users>
    owner: root
    group: tomcat
    mode: '0640'
  notify:
    - restart tomcat

- name: Allow external access to manager
  lineinfile:
    path: /etc/{{ tomcat_package }}/Catalina/localhost/manager.xml
    line: '<Context privileged="true" antiResourceLocking="false" docBase="{catalina.home}/webapps/manager"><Valve className="org.apache.catalina.valves.RemoteAddrValve" allow="^.*$" /></Context>'
    create: yes
  notify:
    - restart tomcat

- name: Configure Tomcat to listen on all interfaces
  replace:
    path: /etc/{{ tomcat_package }}/server.xml
    regexp: '(<Connector port="8080" protocol="HTTP/1.1".*)'
    replace: '\1 address="0.0.0.0"'
  notify:
    - restart tomcat
