---
- name: Installer BIND9 et outils DNS
  apt:
    name:
      - bind9
      - dnsutils
    state: present
    update_cache: yes

- name: Sauvegarder les fichiers de configuration d'origine
  copy:
    src: "{{ item }}"
    dest: "{{ item }}.bkp"
    remote_src: true
  loop:
    - /etc/bind/named.conf.options
    - /etc/bind/named.conf.local

- name: Copier named.conf.options
  copy:
    src: named.conf.options
    dest: /etc/bind/named.conf.options

- name: Copier named.conf.local
  copy:
    src: named.conf.local
    dest: /etc/bind/named.conf.local

- name: Copier la zone directe db.dns.local
  copy:
    src: db.dns.local
    dest: /etc/bind/db.dns.local

- name: Copier la zone inverse db.reverse.dns.local
  copy:
    src: db.reverse.dns.local
    dest: /etc/bind/db.reverse.dns.local

- name: Copier /etc/default/named
  copy:
    src: named.default
    dest: /etc/default/named

- name: Vérification de la config BIND
  command: named-checkconf

- name: Vérification de la zone dns.local
  command: named-checkzone dns.local /etc/bind/db.dns.local

- name: Executer le script send_keys.sh
  shell: |
    sudo bash /vagrant/scripts/config_sys.sh
  args:
    chdir: /vagrant/scripts/

- name: Démarrer le service BIND9
  systemd:
    name: bind9
    state: started
    enabled: true

- name: Redémarrer le service BIND9
  systemd:
    name: bind9
    state: restarted
