---
- name: Mettre à jour les paquets
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Installer les paquets nécessaires
  apt:
    name:
      - borgbackup
      - ansible
      - vagrant
    state: present
  become: true

- name: Créer l’utilisateur proxy avec home directory
  shell: |
    sudo useradd -m -d /home/proxy -s /bin/bash proxy
    echo "proxy:changeme" | sudo chpasswd
    echo "proxy ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/proxy > /dev/null
    sudo chmod 440 /etc/sudoers.d/proxy
  args:
    chdir: /

- name: Préparer le dossier tmp pour Ansible
  become: true
  file:
    path: /home/proxy/.ansible/tmp
    state: directory
    owner: proxy
    group: proxy
    mode: '0700'

- name: Créer le dépôt BorgBackup s’il n’existe pas
  become: true
  become_user: proxy
  environment:
    BORG_PASSPHRASE: changeme
  shell: |
    borg init --encryption=repokey /home/proxy/borg_repo
  args:
    creates: /home/proxy/borg_repo/config

