# -*- mode: ruby -*-
# vi: set ft=ruby :

$script_ssh = <<-SCRIPT
sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config    
sleep 3
service ssh restart
SCRIPT

$script_route = <<-SCRIPT
sudo ip route del default
sudo ip route add default via 192.168.238.1 dev enp0s8
SCRIPT

Vagrant.configure("2") do |config|

	# Number of nodes to provision
	numNodes = 1
 
	# IP Address Base for private network
	ipAddrPrefix1 = "192.168.238."
	
 
	# Define Number of RAM for each node
	config.vm.provider "virtualbox" do |v|
		v.customize ["modifyvm", :id, "--groups", "/projet"]
		v.customize ["modifyvm", :id, "--cpus", "2"]
		v.customize ["modifyvm", :id, "--memory", 2048]
		v.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
		v.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
	end

	 # Download the initial box from this url
 
	 # Provision Config for each of the nodes
	1.upto(numNodes) do |num|
		nodeName = ("zabbix" + num.to_s).to_sym
		config.vm.define nodeName do |node|
			node.vm.host_name = nodeName
			node.vm.box = "chavinje/fr-book-64"
			node.vm.network :public_network, bridge:"eno1", ip: ipAddrPrefix1 + (5).to_s
			node.vm.provider "virtualbox" do |v|
			v.name = "zabbix" + num.to_s
		end

		    node.vm.provision "shell", inline: $script_ssh
        node.vm.provision "shell", path: "scripts/config_ssh.sh"
        node.vm.provision "shell", path: "scripts/config_sys.sh"
		    node.vm.provision "shell", inline: $script_route
		end
	end
        # Number of haproxy nodes to provision
	numRelais = 1

        1.upto(numRelais) do |num|
                relaisName = ("relais").to_sym
                config.vm.define relaisName do |re|
                        re.vm.host_name = relaisName
                        re.vm.box = "chavinje/fr-book-64"
                        re.vm.network :public_network, bridge:"eno1", ip:"192.168.236.10"
                        re.vm.provider "virtualbox" do |v|
                                v.name = "relais" + num.to_s
                        end

                        re.vm.provision "shell", inline: $script_ssh
                        re.vm.provision "shell", path: "scripts/config_ssh.sh"
                        re.vm.provision "shell", path: "scripts/config_sys.sh"
                        re.vm.provision "shell", inline: $script_route
                end
        end

end
