---
- name: Lancer la VM avec Vagrant
  hosts: localhost
  become: false
  tasks:
    - name: Lancer la machine Vagrant
      command: vagrant up
      args:
        chdir: /home/etudis/Bureau/vagrant/
      register: vagrant_up
      changed_when: false
      retries: 3
      delay: 10
      until: vagrant_up is succeeded

    - name: Attendre que le port SSH (22) soit disponible sur la VM
      wait_for:
        host: "{{ groups['mariadb_servers'][0] }}"
        port: 22
        state: started
        delay: 10
        timeout: 5
      register: wait_ssh
      retries: 10
      delay: 5
      until: wait_ssh is succeeded

    - name: Attendre que la VM soit complètement initialisée
      pause:
        seconds: 5
      when: wait_ssh is succeeded

- name: Configure MariaDB Server
  hosts: mariadb_servers
  become: true
  gather_facts: true
  
  pre_tasks:
    - name: Essai de connexion SSH avec réessais
      wait_for_connection:
        delay: 5
        timeout: 30
      register: connection_result
      retries: 5
      delay: 10
      until: connection_result is not failed
      ignore_errors: yes

  roles:
    - role: sys
      tags: [ system, packages ]

    - role: users
      tags: [ users, system ]

- name: Installation et configuration de mariaDB
  hosts: mariadb_servers
  become: true

  roles:
    - role: firewall
      tags: [firewall, security]

    - role: mariadb
      tags: [database, mariadb]

    - role: agent_zabbix
      tags: [monitoring, zabbix]

- name: Vérification de l'installation et de la configuration de MariaDB
  hosts: mariadb_servers
  become: true

  tasks:
    - name: Vérifier que MariaDB est en cours d'exécution
      service:
        name: mariadb
        state: started
      changed_when: false
      tags: [database, services]

    - name: Vérifier que MariaDB écoute sur le bon port
      wait_for:
        port: "{{ mariadb_port }}"
        timeout: "{{ mariadb_connect_timeout }}"
      tags: [database, services]

    - name: Vérifier l'état des services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - mariadb
        - zabbix-agent
      tags: [system, services]
