# -*- mode: ruby -*-
# vi: set ft=ruby :

$script_ssh = <<-SCRIPT
sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config    
sleep 3
service ssh restart
SCRIPT

$script_route = <<-SCRIPT
ip route del default
ip route add default via 192.168.238.1 dev enp0s8
SCRIPT

Vagrant.configure("2") do |config|
  # Serveur virtuel de démonstration
  
  # Define Number of RAM for each node
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--groups", "/projet"]
    v.customize ["modifyvm", :id, "--cpus", "1"]
    v.customize ["modifyvm", :id, "--memory", 512]
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
    v.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
  end

  config.vm.define "zabbix" do |node|
    node.vm.hostname = "zabbix"
    node.vm.box = "chavinje/fr-book-64"
    node.vm.network :public_network, ip: "192.168.238.3"
    node.vm.provision "shell", inline: $script_ssh
		node.vm.provision "shell", inline: $script_route
    #node.vm.provision "shell", path: "scripts/config_sys.sh"
    node.vm.provision "shell", path: "scripts/install_sys.sh"
    node.vm.provision "shell", path: "scripts/install_zabbix_server.sh"
  end 
end
