---
- name: Installer Apache2, PHP, MariaDB, extensions
  apt:
    name:
      - wget
      - gnupg
      - unzip
      - apache2
      - mariadb-client
      - php
      - libapache2-mod-php
      - php-mysql
      - php-intl
      - php-curl
      - php-xmlrpc
      - php-soap
      - php-gd
      - php-json
      - php-cli
      - php-pear
      - php-xml
      - php-zip
      - php-mbstring
      - php-cgi
      - openssl
    state: present
    update_cache: yes

- name: Télécharger PhpMyAdmin si etudiant1
  get_url:
    url: "https://files.phpmyadmin.net/phpMyAdmin/5.2.1/phpMyAdmin-5.2.1-all-languages.zip"
    dest: "/tmp/myadmin.zip"

- name: Décompresser PhpMyAdmin
  unarchive:
    src: /tmp/myadmin.zip
    dest: "/var/www/html"
    remote_src: yes

- name: Créer le lien symbolique vers /myadmin
  file:
    src: "/var/www/html/phpMyAdmin-5.2.1-all-languages"
    dest: "/var/www/html/myadmin"
    state: link

- name: Créer le dossier tmp pour PhpMyAdmin
  file:
    path: "/var/www/html/myadmin/tmp"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Configuration du fichier config.inc.php
  template:
    src: config.inc.php.j2
    dest: "/var/www/html/myadmin/config.inc.php"
    mode: '0644'

- name: Modifier la configuration Apache pour PhpMyAdmin
  copy:
    content: |
      <VirtualHost *:80>
          DocumentRoot /var/www/html/myadmin
          ErrorLog ${APACHE_LOG_DIR}/error.log
          CustomLog ${APACHE_LOG_DIR}/access.log combined
      </VirtualHost>
    dest: "/etc/apache2/sites-available/000-default.conf"

- name: Activer le site Apache
  command: a2ensite 000-default.conf

- name: Restart apache
  service:
    name: apache2
    state: restarted

