# -*- mode: ruby -*-
# vi: set ft=ruby :

$script_ssh = <<-SCRIPT
sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config    
sleep 3
service ssh restart
echo "$(cat /vagrant/files/id_rsa.pub)" >> /home/vagrant/.ssh/authorized_keys
SCRIPT

$script_config = <<-SCRIPT
sudo ip addr flush dev enp0s8
sudo ip addr add 192.168.239.253/29 dev enp0s8
sudo ip route del default
sudo ip route add default via 192.168.239.249 dev enp0s8
sudo echo "search .
nameserver 192.168.238.10" > /etc/resolv.conf
SCRIPT


Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--groups", "/projet"]
    v.customize ["modifyvm", :id, "--cpus", "2"]
    v.customize ["modifyvm", :id, "--memory", 2048]
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
    v.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
  end

  config.vm.define "dhcp-openvpn" do |node|
    node.vm.host_name = "dhcp-openvpn"
    node.vm.box = "chavinje/fr-book-64"
    node.vm.network :public_network, bridge:"enp1s0", ip: "192.168.239.253"
    node.vm.network :public_network, bridge:"eno1", use_dhcp_assigned_default_route: true
    node.vm.provider "virtualbox" do |v|
      v.name = "dhcp-openvpn"
    end

    node.vm.provision "shell", inline: $script_ssh
    node.vm.provision "shell", inline: $script_config
    node.vm.provision "shell", path: "scripts/server.sh"
    node.vm.provision "shell", path: "scripts/client.sh"
  end
end
