# -*- mode: ruby -*-
# vi: set ft=ruby :

$script_ssh = <<-SCRIPT
sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config    
sleep 3
service ssh restart
SCRIPT

$script_route = <<-SCRIPT
sudo ip route del default
sudo ip route add default via 192.168.238.9 dev enp0s8
SCRIPT

Vagrant.configure("2") do |config|

	# Number of nodes to provision
	numNodes = 1
 
	# IP Address Base for private network
	ipAddrPrefix1 = "192.168.238."
	
 
	# Define Number of RAM for each node
	config.vm.provider "virtualbox" do |v|
		v.customize ["modifyvm", :id, "--groups", "/projet"]
		v.customize ["modifyvm", :id, "--cpus", "1"]
		v.customize ["modifyvm", :id, "--memory", 512]
		v.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
		v.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
	end

	 # Download the initial box from this url
 
	 # Provision Config for each of the nodes
	1.upto(numNodes) do |num|
		nodeName = ("srv-dns").to_sym
		config.vm.define nodeName do |node|
			node.vm.host_name = nodeName
			node.vm.box = "chavinje/fr-book-64"
			node.vm.network :public_network, ip: ipAddrPrefix1 + (10).to_s
			node.vm.provider "virtualbox" do |v|
			v.name = "srv-dns"
		end

		node.vm.provision "shell", inline: $script_ssh
        	node.vm.provision "shell", path: "scripts/install_bind.sh"
		node.vm.provision "shell", path: "scripts/config_sys.sh"
		node.vm.provision "shell", inline: $script_route
		end
	end
end
