$script_ssh = <<-SCRIPT
sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config    
sleep 3
service ssh restart
echo "$(cat /vagrant/files/id_rsa.pub)" >> /home/vagrant/.ssh/authorized_keys
SCRIPT

$script_config = <<-SCRIPT
sudo ip addr flush dev enp0s8
sudo ip addr add 192.168.232.15/23 dev enp0s8
sudo echo "search .                     
nameserver 192.168.238.10" > /etc/resolv.conf

sudo ip route del default
sudo ip route add default via 192.168.232.1 dev enp0s8
SCRIPT

Vagrant.configure("2") do |config|

	# Number of nodes to provision
	numNodes = 1
	
 
	# Define Number of RAM for each node
	config.vm.provider "virtualbox" do |v|
		v.customize ["modifyvm", :id, "--groups", "/projet"]
		v.customize ["modifyvm", :id, "--cpus", "2"]
		v.customize ["modifyvm", :id, "--memory", 2048]
		v.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
		v.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
	end

	 # Download the initial box from this url
 
	 # Provision Config for each of the nodes
	1.upto(numNodes) do |num|
		nodeName = ("guacamole1").to_sym
		config.vm.define nodeName do |node|
			node.vm.host_name = nodeName
			node.vm.box = "chavinje/fr-book-64"
			node.vm.network :public_network, bridge:"eno1" ,ip: "192.168.232.15"
			node.vm.provider "virtualbox" do |v|
			v.name = "guacamole1"
		end

		node.vm.provision "shell", inline: $script_ssh
		node.vm.provision "shell", inline: $script_config
   		#node.vm.provision "shell", path: "scripts/install_guacamole.sh"
		end
	end
end
