---
- name: Install required system packages
  apt:
    name:
      - curl
      - apache2
      - libxml2-dev
      - build-essential
    state: present
    update_cache: yes

- name: Add NodeSource repository for Node.js 18
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
  args:
    creates: /etc/apt/sources.list.d/nodesource.list

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Node.js
  apt:
    name:
      - nodejs
    state: present
    update_cache: yes

- name: Ensure correct Node.js version is installed
  command: node --version
  register: node_version
  changed_when: false
  failed_when: "'v18.' not in node_version.stdout"

- name: Enable required Apache modules
  command: a2enmod {{ item }}
  with_items:
    - proxy
    - proxy_http
    - proxy_balancer
    - lbmethod_byrequests
    - rewrite
    - headers
  notify: restart apache
  ignore_errors: yes

- name: Copy deployment platform files
  copy:
    src: deployment_platform
    dest: /opt
    owner: www-data
    group: www-data
    mode: '0644'
    directory_mode: '0755'

- name: Install production dependencies
  npm:
    path: /opt/deployment_platform
    production: yes
    state: present

- name: Ajout des droits sudoer
  lineinfile:
    path: /etc/sudoers
    line: "www-data ALL=(ALL) NOPASSWD: /usr/bin/node /opt/deployment_platform/src/server/index.js"
    state: present

- name: Create systemd service file
  template:
    src: deployment-platform.service.j2
    dest: /etc/systemd/system/deployment-platform.service
    owner: root
    group: root
    mode: '0644'
  notify: reload systemd

- name: Configure Apache site
  template:
    src: apache-deployment-platform.conf.j2
    dest: /etc/apache2/sites-available/deployment-platform.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart apache

- name: Disable default Apache site
  command: a2dissite 000-default.conf
  notify: restart apache
  ignore_errors: yes

- name: Set ServerName to hostname
  lineinfile:
    path: /etc/apache2/apache2.conf
    line: "ServerName {{ ansible_fqdn | default(ansible_hostname) }}"
    insertafter: '^# Global configuration'
    state: present
  notify: restart apache

- name: Enable Apache site
  command: a2ensite deployment-platform.conf
  notify: restart apache

- name: Enable and start deployment platform service
  systemd:
    name: deployment-platform
    enabled: yes
    state: started
    daemon_reload: yes

- name: Set correct permissions
  file:
    path: /opt/deployment_platform
    owner: www-data
    group: www-data
    recurse: yes
