---
- name: Install required system packages
  apt:
    name:
      - nodejs
      - npm
      - apache2
      - libapache2-mod-proxy-html
      - libxml2-dev
      - build-essential
    state: present
    update_cache: yes

- name: Enable required Apache modules
  command: a2enmod proxy proxy_http proxy_balancer lbmethod_byrequests
  notify: restart apache

- name: Create deployment platform directory
  file:
    path: /opt/deployment_platform
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Copy deployment platform files
  copy:
    src: ../../files/
    dest: /opt/deployment_platform/
    owner: www-data
    group: www-data
    mode: '0644'
    directory_mode: '0755'

- name: Install Node.js dependencies
  npm:
    path: /opt/deployment_platform
    state: present

- name: Create .env file
  template:
    src: env.j2
    dest: /opt/deployment_platform/.env
    owner: www-data
    group: www-data
    mode: '0644'

- name: Create systemd service file
  template:
    src: deployment-platform.service.j2
    dest: /etc/systemd/system/deployment-platform.service
    owner: root
    group: root
    mode: '0644'
  notify: reload systemd

- name: Configure Apache
  template:
    src: apache-deployment-platform.conf.j2
    dest: /etc/apache2/sites-available/deployment-platform.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart apache

- name: Enable Apache site
  file:
    src: /etc/apache2/sites-available/deployment-platform.conf
    dest: /etc/apache2/sites-enabled/000-deployment-platform.conf
    state: link
  notify: restart apache

- name: Disable default Apache site
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify: restart apache

- name: Enable and start deployment platform service
  systemd:
    name: deployment-platform
    enabled: yes
    state: started
    daemon_reload: yes

- name: Set correct permissions
  file:
    path: /opt/deployment_platform
    owner: www-data
    group: www-data
    recurse: yes
