$script_ssh = <<-SCRIPT
sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config    
sleep 3
service ssh restart
SCRIPT

$script_route = <<-SCRIPT
sudo ip addr flush dev enp0s8
sudo ip addr add 192.168.238.13/29 dev enp0s8
sudo ip route del default
sudo ip route add default via 192.168.238.9 dev enp0s8

sudo echo "search .                     
nameserver 192.168.4.2" > /etc/resolv.conf
SCRIPT

Vagrant.configure("2") do |config|

	# Number of nodes to provision
	numNodes = 1

	# Define Number of RAM for each node
	config.vm.provider "virtualbox" do |v|
		v.customize ["modifyvm", :id, "--groups", "/projet"]
		v.customize ["modifyvm", :id, "--cpus", "2"]
		v.customize ["modifyvm", :id, "--memory", 2048]
		v.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
		v.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
	end

	 # Download the initial box from this url
 
	 # Provision Config for each of the nodes
	1.upto(numNodes) do |num|
		nodeName = ("ansibleMaster").to_sym
		config.vm.define nodeName do |node|
			node.vm.host_name = nodeName
			node.vm.box = "chavinje/fr-book-64"
			node.vm.network :public_network, ip: "192.168.238.13"
			node.vm.provider "virtualbox" do |v|
			v.name = "ansibleMaster"
		end

		node.vm.provision "shell", inline: $script_ssh
	  node.vm.provision "shell", inline: $script_route
    node.vm.provision "shell", path: "scripts/config_sys.sh"
		node.vm.provision "shell", path: "scripts/send_keys.sh"
		end
	end
end
