---
- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart apache
  service:
    name: apache2
    state: restarted
    enabled: yes

- name: restart deployment platform
  systemd:
    name: deployment-platform
    state: restarted
    daemon_reload: yes
