---
- name: Creer le fichier de configuration Galera
  template:
    src: 60-galera.cnf
    dest: /etc/mysql/mariadb.conf.d/60-galera.cnf
    owner: root
    group: root
    mode: '0644'

- name: Redemarrer MariaDB
  service:
    name: mariadb
    state: restarted
    
- name: Creer les bases et utilisateurs si on est sur galeranode3
  shell: |
    mysql -u root <<EOF
    CREATE DATABASE IF NOT EXISTS etudiant1;
    CREATE DATABASE IF NOT EXISTS etudiant2;
    CREATE USER IF NOT EXISTS 'admin'@'%' IDENTIFIED BY 'network';
    CREATE USER IF NOT EXISTS 'etudiant1'@'%' IDENTIFIED BY 'network';
    CREATE USER IF NOT EXISTS 'etudiant2'@'%' IDENTIFIED BY 'network';
    GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%' WITH GRANT OPTION;
    GRANT ALL PRIVILEGES ON etudiant1.* TO 'etudiant1'@'%';
    GRANT ALL PRIVILEGES ON etudiant2.* TO 'etudiant2'@'%';
    FLUSH PRIVILEGES;
    EOF
