- name: Attente des machines distantes
  hosts:
    - Firewall
  gather_facts: false
  tasks:
    - name: Attendre que la machine soit accessible en SSH
      wait_for_connection:
        timeout: 5
      register: ssh_check
      until: ssh_check is succeeded
      retries: 30
      delay: 5

- name: Deploiement DHCP
  hosts:
    - Firewall
  become: false
  roles:
    - DHCP_openVPN
