---
- name: Install PostgreSQL and its dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - postgresql
    - postgresql-contrib
    - libpq-dev
    - python3-psycopg2

- name: Ensure PostgreSQL is running and enabled on boot
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Create PostgreSQL database
  postgresql_db:
    name: "{{ db_name }}"
    encoding: 'UTF-8'
    lc_ctype: 'en_US.UTF-8'
    lc_collate: 'en_US.UTF-8'
    state: present
  become_user: postgres

- name: Create PostgreSQL user with password
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    db: "{{ db_name }}"
    priv: "ALL"
    role_attr_flags: "CREATEDB,LOGIN"
  become_user: postgres
  no_log: true  # Ne pas afficher le mot de passe dans les logs

- name: Update PostgreSQL configuration to allow remote connections
  lineinfile:
    path: /etc/postgresql/*/main/postgresql.conf
    line: "{{ item }}"
    regexp: "^#?listen_addresses"
  with_items:
    - "listen_addresses = '*'"
  notify:
    - restart postgresql

- name: Update pg_hba.conf to allow connections
  lineinfile:
    path: /etc/postgresql/*/main/pg_hba.conf
    line: "host    all             all             0.0.0.0/0               md5"
    insertafter: '^# IPv4 local connections:'
  notify:
    - restart postgresql
